#!/bin/sh

PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH

pipework --wait

reg() {
    for sec in 1 1 2 3 5 8 5 3 2 1; do 
        sleep $sec
        register
    done
}

reg 2>&1 /var/tmp/register.log &

set -e
nginx

sleep infinity
